basePath: /api/v1
definitions:
  structs.Responce:
    properties:
      msg:
        type: string
    type: object
  structs.Subscription:
    properties:
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для управления подписками пользователей на сервисы
  title: Subscription API
  version: "1.0"
paths:
  /:
    get:
      description: Возвращает список всех подписок с возможностью фильтрации
      parameters:
      - description: Фильтр по названию сервиса
        in: query
        name: service_name
        type: string
      - description: Фильтр по цене
        in: query
        name: price
        type: integer
      - description: Фильтр по ID пользователя
        in: query
        name: user_id
        type: string
      - description: Фильтр по дате начала (MM-YYYY)
        in: query
        name: start_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/structs.Subscription'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/structs.Responce'
      summary: Список всех подписок
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Создает новую запись подписки
      parameters:
      - description: Данные подписки
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/structs.Subscription'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/structs.Subscription'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/structs.Responce'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/structs.Responce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/structs.Responce'
      summary: Создать новую подписку
      tags:
      - subscriptions
  /{service_name}/{user_id}:
    delete:
      description: Удаляет подписку по имени сервиса и ID пользователя
      parameters:
      - description: Название сервиса
        in: path
        name: service_name
        required: true
        type: string
      - description: ID пользователя
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.Responce'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/structs.Responce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/structs.Responce'
      summary: Удалить подписку
      tags:
      - subscriptions
    get:
      description: Возвращает информацию о подписке по имени сервиса и ID пользователя
      parameters:
      - description: Название сервиса
        in: path
        name: service_name
        required: true
        type: string
      - description: ID пользователя
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.Subscription'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/structs.Responce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/structs.Responce'
      summary: Получить подписку
      tags:
      - subscriptions
    patch:
      consumes:
      - application/json
      description: Обновляет существующую подписку
      parameters:
      - description: Название сервиса
        in: path
        name: service_name
        required: true
        type: string
      - description: ID пользователя
        in: path
        name: user_id
        required: true
        type: string
      - description: Данные для обновления (только цена)
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/structs.Subscription'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.Subscription'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/structs.Responce'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/structs.Responce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/structs.Responce'
      summary: Обновить подписку
      tags:
      - subscriptions
  /totalPrice:
    get:
      description: Возвращает общую стоимость подписок за указанный период
      parameters:
      - description: Дата начала периода (MM-YYYY)
        in: query
        name: from
        required: true
        type: string
      - description: Фильтр по названию сервиса
        in: query
        name: service_name
        type: string
      - description: Фильтр по ID пользователя
        in: query
        name: user_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/structs.Responce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/structs.Responce'
      summary: Общая стоимость подписок за период
      tags:
      - subscriptions
schemes:
- http
swagger: "2.0"
