name: test-effective-mobile

services:
  db:
    container_name: db
    image: postgres:latest
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db
    ports: 
      - "5432:5432"
    volumes: 
      - "postgres_data:/var/lib/postgresql"
    healthcheck:
      test: [CMD-SHELL, "pg_isready -U admin -d db"]
      interval: 10s
      timeout: 5s
      retries: 3

  migrate:
    container_name: migrate
    build:
      dockerfile: dockerfile.migrate
    depends_on:
      db:
        condition: service_healthy
    environment: 
        - CONNECTION_CFG=postgresql://admin:admin@db:5432/db?sslmode=disable
    command: >
      sh -c '
      migrate -path /migrations -database $$CONNECTION_CFG up
      '

volumes:
  postgres_data: