name: test-effective-mobile

services:
  db:
    container_name: db
    image: postgres:latest
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db
    ports: 
      - "5432:5432"
    volumes: 
      - "postgres_data:/var/lib/postgresql"
    healthcheck:
      test: [CMD-SHELL, "pg_isready -U admin -d db"]
      interval: 10s
      timeout: 5s
      retries: 3
#    secrets:
#      - postgres_password
volumes:
  postgres_data:
#secrets:
#  postgres_password:
#    file: ../postgres_password.txt